repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    -   id: end-of-file-fixer
    -   id: check-toml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.2.3
  hooks:
    - id: nbqa
      args: [isort]
      name: nbqa-isort
      alias: nbqa-isort
      additional_dependencies: [isort]
    - id: nbqa
      args: [black]
      name: nbqa-black
      alias: nbqa-black
      additional_dependencies: [black]
    - id: nbqa
      args: [pyupgrade]
      name: nbqa-pyupgrade
      alias: nbqa-pyupgrade
      additional_dependencies: [pyupgrade]
    - id: nbqa
      args: [flake8]
      name: nbqa-flake8
      alias: nbqa-flake8
      additional_dependencies: [flake8]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.2
  hooks:
    - id: pyupgrade
      args: ['--py36-plus']
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
