repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.3.0
  hooks:
    - id: nbqa
      args: [isort]
      name: nbqa-isort
      alias: nbqa-isort
      additional_dependencies: [isort]
    - id: nbqa
      args: [black]
      name: nbqa-black
      alias: nbqa-black
      additional_dependencies: [black]
    - id: nbqa
      args: [pyupgrade]
      name: nbqa-pyupgrade
      alias: nbqa-pyupgrade
      additional_dependencies: [pyupgrade]
    - id: nbqa
      args: [flake8]
      name: nbqa-flake8
      alias: nbqa-flake8
      additional_dependencies: [flake8]
