[tool.black]
line-length = 79

[tool.nbqa.config]
flake8 = "setup.cfg"
isort = "setup.cfg"
black = "pyproject.toml"

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1

[tool.nbqa.addopts]
pyupgrade = ["--py38-plus"]
